// ============================================
// mobile/src/screens/orders/OrderSuccessScreenPremiumStyles.js
// ============================================
import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  'order-success-premium-screen': {
    flex: 1,
    backgroundColor: '#FFFFFF', // Fallback
  },
  'gradient': {
    flex: 1,
    padding: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  'order-success-premium-animation': {
    alignItems: 'center',
    marginBottom: 40,
  },
  'order-success-premium-circle': {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  'order-success-premium-circle-inner': {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 12,
  },
  'order-success-premium-title': {
    fontSize: 32,
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 10,
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  'order-success-premium-subtitle': {
    fontSize: 17,
    color: 'rgba(255, 255, 255, 0.85)',
    textAlign: 'center',
    marginBottom: 40,
    fontWeight: '600',
  },
  'order-success-premium-details-card': {
    width: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 24,
    padding: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  'order-success-premium-detail-row': {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
  },
  'order-success-premium-detail-label': {
    fontSize: 15,
    color: 'rgba(255, 255, 255, 0.7)',
    fontWeight: '600',
  },
  'order-success-premium-detail-value': {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  'order-success-premium-detail-value-highlight': {
    fontSize: 24,
    color: '#FFFFFF',
    fontWeight: '900',
  },
  'order-success-premium-payment-badge': {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 8,
  },
  'order-success-premium-divider': {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
  },
  'order-success-premium-delivery-info': {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    padding: 18,
    borderRadius: 20,
    marginBottom: 32,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  'order-success-premium-delivery-icon-wrapper': {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  'order-success-premium-delivery-info-text': {
    flex: 1,
  },
  'order-success-premium-delivery-info-title': {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.6)',
    fontWeight: '600',
    marginBottom: 4,
  },
  'order-success-premium-delivery-info-address': {
    fontSize: 17,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  'order-success-premium-action-buttons': {
    width: '100%',
    gap: 16,
    marginBottom: 32,
  },
  'order-success-premium-btn-track-order': {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: 20,
    borderRadius: 20,
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  'order-success-premium-btn-track-order-text': {
    fontSize: 18,
    fontWeight: '800',
    color: '#4F46E5',
  },
  'order-success-premium-btn-continue-shopping': {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    paddingVertical: 18,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  'order-success-premium-btn-continue-shopping-text': {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  'order-success-premium-help-section': {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  'order-success-premium-help-text': {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.7)',
    fontWeight: '600',
  },
});