// ============================================
// mobile/src/screens/orders/OrderDetailsScreenPremiumStyles.js
// ============================================
import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  'order-details-premium-container': {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  'order-details-premium-header-card': {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 12,
    padding: 20,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 5,
  },
  'order-details-premium-order-number': {
    fontSize: 24,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: 6,
  },
  'order-details-premium-order-date': {
    fontSize: 14,
    color: '#4A4A4A',
    fontWeight: '500',
  },
  'order-details-premium-timeline-card': {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 20,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 5,
  },
  'order-details-premium-section-title': {
    fontSize: 18,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: 16,
  },
  'order-details-premium-timeline-container': {
    paddingLeft: 8,
  },
  'order-details-premium-timeline-step': {
    flexDirection: 'row',
    alignItems: 'flex-start',
    position: 'relative',
  },
  'order-details-premium-timeline-left': {
    alignItems: 'center',
    marginRight: 16,
  },
  'order-details-premium-timeline-dot': {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#F5F7FA',
  },
  'order-details-premium-timeline-dot-done': {
    backgroundColor: '#0A84FF',
  },
  'order-details-premium-timeline-line': {
    width: 3,
    height: 40,
    backgroundColor: '#E5E7EB',
    marginVertical: 4,
  },
  'order-details-premium-timeline-line-done': {
    backgroundColor: '#0A84FF',
  },
  'order-details-premium-timeline-content': {
    paddingVertical: 6,
    flex: 1,
  },
  'order-details-premium-timeline-label': {
    fontSize: 16,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  'order-details-premium-timeline-label-done': {
    color: '#1A1A1A',
  },
  'order-details-premium-tracking-card': {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(10, 132, 255, 0.05)',
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 18,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(10, 132, 255, 0.15)',
  },
  'order-details-premium-tracking-icon-wrapper': {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  'order-details-premium-tracking-info': {
    flex: 1,
  },
  'order-details-premium-tracking-label': {
    fontSize: 13,
    color: '#4A4A4A',
    fontWeight: '500',
    marginBottom: 4,
  },
  'order-details-premium-tracking-number': {
    fontSize: 16,
    fontWeight: '700',
    color: '#0A84FF',
    letterSpacing: 0.5,
  },
  'order-details-premium-tracking-btn': {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  'order-details-premium-section-card': {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 20,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 5,
  },
  'order-details-premium-section-header': {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 8,
  },
  'order-details-premium-item-card': {
    flexDirection: 'row',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F7FA',
  },
  'order-details-premium-item-image-wrapper': {
    width: 90,
    height: 90,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#F5F7FA',
    marginRight: 14,
  },
  'order-details-premium-item-image': {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  'order-details-premium-item-info': {
    flex: 1,
    justifyContent: 'center',
  },
  'order-details-premium-item-title': {
    fontSize: 16,
    fontWeight: '600',
    color: '#1A1A1A',
    marginBottom: 6,
  },
  'order-details-premium-item-quantity': {
    fontSize: 14,
    color: '#4A4A4A',
    marginBottom: 6,
  },
  'order-details-premium-item-price': {
    fontSize: 18,
    fontWeight: '700',
    color: '#0A84FF',
  },
  'order-details-premium-address-box': {
    backgroundColor: '#F5F7FA',
    padding: 16,
    borderRadius: 14,
  },
  'order-details-premium-address-name': {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: 8,
  },
  'order-details-premium-address-text': {
    fontSize: 14,
    color: '#4A4A4A',
    lineHeight: 20,
    marginBottom: 4,
  },
  'order-details-premium-phone-wrapper': {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
  },
  'order-details-premium-address-phone': {
    fontSize: 14,
    color: '#4A4A4A',
    fontWeight: '600',
  },
  'order-details-premium-price-container': {
    backgroundColor: '#F5F7FA',
    padding: 16,
    borderRadius: 14,
  },
  'order-details-premium-price-row': {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  'order-details-premium-price-label': {
    fontSize: 15,
    color: '#4A4A4A',
    fontWeight: '500',
  },
  'order-details-premium-price-value': {
    fontSize: 15,
    color: '#1A1A1A',
    fontWeight: '600',
  },
  'order-details-premium-price-divider': {
    height: 1,
    backgroundColor: '#D1D5DB',
    marginVertical: 12,
  },
  'order-details-premium-price-row-total': {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 4,
  },
  'order-details-premium-price-label-total': {
    fontSize: 18,
    color: '#1A1A1A',
    fontWeight: '700',
  },
  'order-details-premium-price-value-total': {
    fontSize: 22,
    color: '#0A84FF',
    fontWeight: '800',
  },
  'order-details-premium-actions': {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginBottom: 12,
    gap: 12,
  },
  'order-details-premium-action-btn': {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#0A84FF',
    gap: 8,
    shadowColor: '#0A84FF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  'order-details-premium-action-text': {
    fontSize: 15,
    fontWeight: '600',
    color: '#0A84FF',
  },
  'order-details-premium-bottom-spacer': {
    height: 30,
  },
});