// ============================================
// mobile/src/screens/payment/PaymentScreenPremiumStyles.js
// ============================================
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  'payment-premium-processing-screen': {
    flex: 1,
    backgroundColor: '#F5F7FA',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  'payment-premium-processing-animation': {
    marginBottom: 32,
  },
  'payment-premium-processing-title': {
    fontSize: 24,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: 8,
    textAlign: 'center',
  },
  'payment-premium-processing-subtitle': {
    fontSize: 15,
    color: '#4A4A4A',
    textAlign: 'center',
    marginBottom: 24,
  },
  'payment-premium-processing-amount': {
    fontSize: 36,
    fontWeight: '800',
    color: '#0A84FF',
    marginBottom: 32,
  },
  'payment-premium-secure-badge': {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    gap: 8,
  },
  'payment-premium-secure-text': {
    fontSize: 14,
    color: '#10B981',
    fontWeight: '600',
  },
  'payment-premium-result-screen': {
    flex: 1,
    backgroundColor: '#F5F7FA',
    padding: 24,
    justifyContent: 'center',
  },
  'payment-premium-success-animation': {
    alignItems: 'center',
    marginBottom: 32,
  },
  'payment-premium-success-circle': {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  'payment-premium-success-circle-inner': {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#10B981',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 10,
  },
  'payment-premium-fail-animation': {
    alignItems: 'center',
    marginBottom: 32,
  },
  'payment-premium-fail-circle': {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  'payment-premium-fail-circle-inner': {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#EF4444',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 10,
  },
  'payment-premium-result-title': {
    fontSize: 28,
    fontWeight: '800',
    color: '#1A1A1A',
    textAlign: 'center',
    marginBottom: 8,
  },
  'payment-premium-result-title-fail': {
    fontSize: 28,
    fontWeight: '800',
    color: '#EF4444',
    textAlign: 'center',
    marginBottom: 8,
  },
  'payment-premium-result-subtitle': {
    fontSize: 16,
    color: '#4A4A4A',
    textAlign: 'center',
    marginBottom: 32,
    fontWeight: '500',
  },
  'payment-premium-order-info-box': {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 5,
  },
  'payment-premium-info-row': {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
  },
  'payment-premium-info-label': {
    fontSize: 15,
    color: '#4A4A4A',
    fontWeight: '500',
  },
  'payment-premium-info-value': {
    fontSize: 15,
    color: '#1A1A1A',
    fontWeight: '700',
  },
  'payment-premium-info-value-highlight': {
    fontSize: 22,
    color: '#0A84FF',
    fontWeight: '800',
  },
  'payment-premium-divider': {
    height: 1,
    backgroundColor: '#F5F7FA',
  },
  'payment-premium-error-info-box': {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    padding: 16,
    borderRadius: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.2)',
    gap: 12,
  },
  'payment-premium-error-message': {
    flex: 1,
    fontSize: 14,
    color: '#4A4A4A',
    lineHeight: 20,
  },
  'payment-premium-delivery-estimate': {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(10, 132, 255, 0.08)',
    padding: 14,
    borderRadius: 14,
    marginBottom: 24,
    gap: 8,
  },
  'payment-premium-delivery-text': {
    fontSize: 14,
    color: '#1A1A1A',
    fontWeight: '600',
  },
  'payment-premium-action-buttons': {
    gap: 12,
  },
  'payment-premium-btn-view-order': {
    backgroundColor: '#0A84FF',
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: '#0A84FF',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  'payment-premium-btn-view-order-text': {
    fontSize: 17,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  'payment-premium-btn-continue-shopping': {
    backgroundColor: '#FFFFFF',
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#0A84FF',
  },
  'payment-premium-btn-continue-shopping-text': {
    fontSize: 16,
    fontWeight: '700',
    color: '#0A84FF',
  },
  'payment-premium-btn-retry': {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0A84FF',
    paddingVertical: 18,
    borderRadius: 16,
    gap: 10,
    shadowColor: '#0A84FF',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  'payment-premium-btn-retry-text': {
    fontSize: 17,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  'payment-premium-btn-cancel': {
    backgroundColor: '#FFFFFF',
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#EF4444',
  },
  'payment-premium-btn-cancel-text': {
    fontSize: 16,
    fontWeight: '700',
    color: '#EF4444',
  },
});